apiVersion: v2
appVersion: '1.0'
description: A Helm chart for jps-judicial-payment-frontend App
name: jps-judicial-payment-frontend
home: https://github.com/hmcts/jps-judicial-payment-frontend
version: 0.0.5
dependencies:
  - name: nodejs
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: idam-pr
    version: ~2.1.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - idam-pr
