nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

idam-pr:
  enabled: true
  redirect_uris:
    jps_judicial_payment_frontend:
      - https://${SERVICE_FQDN}/oauth2/callback