nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SERVICES_IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    SERVICES_IDAM_LOGIN_URL: https://idam-web-public.aat.platform.hmcts.net
    DEBUG: xuiNode:*,-xuiNode:auth:s2s,-xuiNode:auth:oauth2
  autoscaling:
    enabled: false
idam-pr:
  enabled: true
  redirect_uris:
    XUI:
      - https://${SERVICE_FQDN}/oauth2/callback
